[app-servers]
# Multiple FRR routers
# All variables are defined in vars/frr_vars.yml

z1scuti03 ansible_host=10.30.19.6 ansible_user=ubuntu

[app-servers:vars]
# Common variables for all servers
ansible_become=yes
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
